Repository dolbyio-samples/comms-app-react-native-videocall, pull requests merged in 2022-12, with the labels that each got.

#44 Internal test builds - iOS
  .github/workflows/cd_ios.yml
  examples/mobile/ios/Configuration/InternalReleaseSettings.xcconfig
  examples/mobile/ios/DolbyIOVideoCall.xcodeproj/project.pbxproj
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon-Internal.appiconset/AppIconInternal-1024x1024.png
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon-Internal.appiconset/Contents.json
  examples/mobile/ios/fastlane/.env.appstoreInternal
Labels: CI/CD, iOS, CLA Signed

#48 Update github action name for ruby
  .github/workflows/cd_ios.yml
Labels: CLA Signed

#47 [Android] Internal app build and distribution
  .github/workflows/cd_android.yml
  examples/mobile/android/app/build.gradle
  examples/mobile/android/app/src/internal/ic_launcher-playstore.png
  examples/mobile/android/app/src/internal/res/drawable/ic_launcher_background.xml
  examples/mobile/android/app/src/internal/res/mipmap-anydpi-v26/ic_launcher.xml
  examples/mobile/android/app/src/internal/res/mipmap-anydpi-v26/ic_launcher_round.xml
  examples/mobile/android/app/src/internal/res/mipmap-hdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-hdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-hdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-mdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-mdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-mdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-xhdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-xhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-xhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-xxhdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-xxhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-xxhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-xxxhdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-xxxhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/values/strings.xml
  examples/mobile/package.json
Labels: CI/CD, Android, CLA Signed

#51 Update App name for Internal builds
  examples/mobile/ios/Configuration/InternalReleaseSettings.xcconfig
  examples/mobile/ios/DolbyIOVideoCall.xcodeproj/project.pbxproj
  examples/mobile/ios/DolbyIOVideoCall/Info.plist
Labels: iOS, CLA Signed

#45 Add features and known issues doc
  KNOWN-ISSUES.md
  README.md
Labels: CLA Signed

#54 Updated Third-party Licenses file
  third-party-licenses.json
Labels: CLA Signed

#52 Update App Icon
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon-Internal.appiconset/AppIconInternal-1024x1024.png
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon-Internal.appiconset/Contents.json
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon-Internal.appiconset/Dolby IO–apple–1024_fullBleed_logo_internal.png
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon.appiconset/AppIcon-1024x1024.png
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon.appiconset/Contents.json
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon.appiconset/Dolby IO–apple–1024_fullBleed_logo_product.png
Labels: iOS, CLA Signed

#53 Android App Icons
  examples/mobile/android/app/src/internal/ic_launcher-playstore.png
  examples/mobile/android/app/src/internal/res/mipmap-hdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-hdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-hdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-mdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-mdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-mdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-xhdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-xhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-xhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-xxhdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-xxhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-xxhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/internal/res/mipmap-xxxhdpi/ic_launcher.png
  examples/mobile/android/app/src/internal/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/internal/res/mipmap-xxxhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/main/ic_launcher-playstore.png
  examples/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  examples/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  examples/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  examples/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  examples/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  examples/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  examples/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  examples/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  examples/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  examples/mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: Android, CLA Signed

#55 Update readme
  README.md
  examples/mobile/package.json
  third-party-licenses.json
Labels: documentation, CLA Signed

#58 Removes the Alpha Channel in the App Icons
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon-Internal.appiconset/Dolby IO–apple–1024_fullBleed_logo_internal.png
  examples/mobile/ios/DolbyIOVideoCall/Images.xcassets/AppIcon.appiconset/Dolby IO–apple–1024_fullBleed_logo_product.png
Labels: CLA Signed

#59 IOPS-927 Add license checker
  .github/actions/npm-license-checker-pr/action.yml
  .github/workflows/license-checker.yml
  third-party-licenses.json
Labels: CLA Signed

#61 Web association files
  examples/mobile/association/apple-app-site-association
  examples/mobile/association/assetlinks.json
Labels: CLA Signed
